### ISSUE TITLE
Přesun pod oficiální URL

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-gis-convert#17]
Aplikaci je třeba prozatím na aktuálním serveru přesunout pod adresu: https://amcr-convert.aiscr.cz/

@MichalKminek Prosím o založení adresy a domluvu s @tomvojtechovsky na nastavení DNS.

**Comment by MichalKminek** [comment]
Uchystal bych DNS zaznam, potrebuji verejnou adresu, kde projekt bezi a kde ma byt dostupny na vyse uvedene adrese.

**Comment by tomvojtechovsky** [comment]
shptowkt.geogrep.cz 
80.211.208.207
TTL 1800
Typ A

**Comment by MichalKminek** [comment]
Nastaveno
amcr-convert.aiscr.cz.  586     IN      CNAME   shptowkt.geogrep.cz.
shptowkt.geogrep.cz.    1786    IN      A       80.211.208.207

Prosim konfigurujte domenu amcr-convert.aiscr.cz na svem web serveru. Dekuji

**Comment by tomvojtechovsky** [comment]
### Nasazení nové produkční domény
https://amcr-convert.aiscr.cz/

1. **Přidána nová doména**: `amcr-convert.aiscr.cz`
    - Doména byla nastavena jako alias k serveru `shptowkt.geogrep.cz`
    - Přesměrování z HTTP na HTTPS bylo nakonfigurováno pomocí Let's Encrypt certifikátu.

2. **Konfigurace Apache**:
    - Vytvořen nový virtuální host pro `amcr-convert.aiscr.cz`, včetně SSL certifikace.

3. **Zachování dynamického API**:
    - Byla implementována dynamická detekce API URL v aplikaci, která rozlišuje mezi doménami `shptowkt.geogrep.cz` a `amcr-convert.aiscr.cz`.
    - Aplikace nyní automaticky volí správnou API URL podle toho, z jaké domény je načtena, bez nutnosti manuálních změn v kódu.


Aplikace je nyní úspěšně nasazena a funkční na nové produkční doméně `amcr-convert.aiscr.cz`.

**Comment by MichalKminek** [comment]
Dekuji, funguje se SSL jak ma.

**Comment by motyc** [comment]
Také potvrzuji a zavírám.
