### ISSUE TITLE
Ukládání souborů

### ISSUE THREAD

**Issue by tomvojtechovsky** [ARUP-CAS/aiscr-gis-convert#2]
Aktuálně se nahrané soubory ukládají na disk před jejich zpracováním. Nově by měly být pouze v paměti (in-memory).

**Comment by tomvojtechovsky** [comment]
**Bohužel**
Po důkladném prozkoumání možnosti implementace zpracování shapefilů pouze v paměti (in-memory) jsem se rozhodl zachovat současné řešení s ukládáním na disk. Hlavní důvod je:

**Problém s DBF soubory**
Zpracování DBF souborů v paměti se ukázalo jako velmi problematické. DBF (dBase) je starší formát databázových souborů a práce s těmito soubory se zdá být poměrně komplikovaná kvůli různým verzím formátu, rozdílným kódováním znaků a nedostatku moderní podpory. 

**Vyzkoušena celá řada knihoven**
Vyzkoušel jsem knihovny jako `dbffile`, `node-dbf`, `dbf-reader`, `shapefile.js` a některé další, ale žádná neposkytla spolehlivé řešení pro in-memory zpracování DBF souborů.  Velkým problémem bylo již samotné čtení DBF souborů z paměti a vzhledem k počtu pokusů správně dekódovat hodnoty atributů jsem zvážil, že in memory je momentálně příliš náročné řešení. 

**Řešení**
Místo implementace in-memory zpracování se zaměřím na vylepšení stávajícího řešení.

- bezpečné mazání dočasných souborů
- případná dodatečná bezpečnostní opatření pro práci s dočasnými soubory

**Comment by motyc** [comment]
@tomvojtechovsky Díky za protestování. Určitě souhlasím s návrhem. Případné drobné nedostatky doladíme, až představíte novou verzi.

**Comment by tomvojtechovsky** [comment]
Soubory se ukládají na disk a ihned po zpracování jsou smazány z disku.
Přidal jsem funkci, která každé 4 hodiny smaže uložená data, pokud se náhodou nějaký soubor nesmaže.
