### ISSUE TITLE
EPSG - S-JTSK

### ISSUE THREAD

**Issue by tomvojtechovsky** [ARUP-CAS/aiscr-gis-convert#20]
- Indikace EPSG ze zdrojového souboru funguje při správných EPSG kódech správně.
- Při pokusu použít místo *S-JTSK / Krovak East North (EPSG: 5514)* variantu *S-JTSK (Ferro) / Krovak East North (EPSG: 5221)*:
  - Konvertor to identifikoval jako EPSG: 5514.
  - Data byla po importu do AMČR posunutá.
  
- Pravděpodobnost, že někdo použije EPSG: 5221 místo EPSG: 5514, může být malá, ale problém s posunem dat může nastat.

**Comment by tomvojtechovsky** [comment]
@svejci, pokud bychom chtěli můžeme se např. pokusit identifikovat jakékoli S-JTSK a převést to na 5514.

**Comment by motyc** [comment]
@tomvojtechovsky Jestli to není nijak extra komplikované a nehrozí chyby, tak mi to přijde jako super řešení.

**Comment by tomvojtechovsky** [comment]
Při nahrání SHP dojde ke kontrole, zda SHP (dle PRJ souboru) není jedním z níže uvedených. Pokud ano, aplikace se pokusí o tranformaci. Následně je uživatel infomován.

| EPSG Code | Search Text                      |
|-----------|----------------------------------|
| 2065      | S-JTSK_Ferro_Krovak              |
| 5221      | S-JTSK_Ferro_Krovak_East_North   |
| 8352      | S-JTSK_JTSK03_Krovak             |
| 8353      | S-JTSK_JTSK03_Krovak_East_North  |
| 5513      | S-JTSK_Krovak                    |
| 5514      | S-JTSK_Krovak_East_North         |
| 102066    | S-JTSK_Ferro_Krovak_East_North   |
| 102065    | S-JTSK_Krovak                    |
| 102067    | S-JTSK_Krovak_East_North         |


![image](https://github.com/user-attachments/assets/34edb6ec-d16a-4f91-a367-3225b3b1657e)
